### PR TITLE
Fix macos build

### PR DESCRIPTION
**Pull request by elmart-devo**
Important commit that solves https://github.com/gliwka/hyperscan-java/issues/114 is the first one.
The other ones are extra improvements I needed to do while fixing this on a macos machine, which I think you can find useful too.
Read full commit messages for more details.

### CODE REVIEW

**Review by gliwka — APPROVED** [review]

**Comment by gliwka** [comment]
Thank you for noticing and making it easier to run locally. Verified it on my OS X machine. Calling ./build.sh now works like a charm.

**Comment by elmart-devo** [comment]
You're welcome. Glad to help.

**Comment by elmart-devo** [comment]
It seems the merge to main failed to pass checks.

**Comment by gliwka** [comment]
Will fix it on the weekend and release it to maven (finally).

**Pull request merged**
